spring.application.name=Core


# Spring Boot application name
spring.datasource.url=jdbc:postgresql://localhost:5433/StudyBuddy
spring.datasource.username=postgres
spring.datasource.password=123qweasdzxc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.session.jdbc.initialize-schema=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8080


jwt.secret-base64=false
jwt.secret=this_is_a_very_long_secret_key_at_least_32_chars
jwt.expiration-millis=3600000
jwt.issuer=StudyBuddy

app.upload.dir=uploads

google.client-id=535168158972-almaug51ukesib2qg241kem05dh0uq8g.apps.googleusercontent.com

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


