package model;

public enum Subject {
    JAVA,
    PYTHON,
    DATABASES,
    NETWORKS,
    ALGORITHMS,
    DATA_STRUCTURES,
    OPERATING_SYSTEMS,
    WEB_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    SOFTWARE_ENGINEERING,
    CYBERSECURITY,
    ARTIFICIAL_INTELLIGENCE,
    MACHINE_LEARNING,
    COMPUTER_GRAPHICS,
    DISCRETE_MATH,
    EMBEDDED_DEVELOPMENT,
    TZIV,
    MATHANALYSYS,
    PPI_dontrespectit,
}
